name: Generate Snake

on:
  schedule:
    - cron: "30 5,17 * * *" # Runs every 6 hours
  workflow_dispatch: # Allows manual trigger from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }} # Automatically uses your username
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-contribution-grid-snake.gif

      - name: Commit and Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          branch: output
          force: true

      - name: Deploy SVG via GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
